apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
  - hosts:
    - {{ template "ingress.host.effective" . }}
    secretName: {{ template "ingress.host.effective" . }}
  rules:
  - host: {{ template "ingress.host.effective" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-{{ .Chart.Name }}"
          servicePort: 3000