apiVersion: v1
kind: ConfigMap
metadata:
  name: production-config
data:
  config.json: |-
    {
      "system": {
          "host": "Your Host",
          "port": "443",
          "protocol": "https",
          "logger": {
              "type": "console"
          },
          "subDomainCookies": true,
          "muteNotifications": true
      },
      "express": {
          "key": "<<Express Key>>"
      },
      "apn": {
          "gateway": "gateway.push.apple.com",
          "cert": "certs/aps/aps_dev_cert.pem",
          "key": "certs/aps/aps_dev_key.pem",
          "passphrase": "passphrase"
      },
      "gcm": {
          "jid": "yourappid@gcm.googleapis.com",
          "password": "passphrase"
      },
      "ifttt": {
          "iftttChannelKey": "iftttkey",
          "iftttTestToken": "ifttttoken"
      },
      "mail": {
          "host" : "mailhost",
          "port": 465,
          "user": "",
          "pass": ""
      },
      "mongodb": {
          "hosts": [
              "mongodb"
          ],
          "db": "openhab"
      },
      "redis": {
          "host": "redis",
          "port": "6379"
      },
      "mailer": {
          "host" : "mailhost",
          "port": 465,
          "secureConnection": true,
          "user": "",
          "password": "",
          "from": "support@foo.com"
      },
      "legal": {
          "terms": "http://www.myopenhab.org/terms.html",
          "policy": "http://www.myopenhab.org/privacy"
      }
    }
  envoy.yaml: |-
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    static_resources:
      listeners:
      - name: listener_http
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 80
        filter_chains:
        - use_proxy_proto: true
          filters:
          - name: envoy.http_connection_manager
            config:
              access_log:
              - name: envoy.file_access_log
                config:
                  path: "/dev/stdout"
              upgrade_configs:
                upgrade_type: "websocket"
              stat_prefix: ingress_http
              route_config:
                name: local_route_http
                virtual_hosts:
                - name: local_service_http
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    redirect: { https_redirect: true }
              http_filters:
              - name: envoy.router
      - name: listener_https
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 81
        filter_chains:
        - use_proxy_proto: true
          filters:
          - name: envoy.http_connection_manager
            config:
              access_log:
              - name: envoy.file_access_log
                config:
                  path: "/dev/stdout"
              upgrade_configs:
                upgrade_type: "websocket"
              stat_prefix: ingress_http
              route_config:
                name: local_route_https
                virtual_hosts:
                - name: local_service_https
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/socket.io"
                    route:
                      cluster: proxy_app_cluster
                      timeout: 60s 
                      hash_policy:
                        header:
                          header_name: "uuid"
                  - match:
                      prefix: "/"
                    route:
                      cluster: web_app_cluster
                      timeout: 60s 
              http_filters:
              - name: envoy.router
      clusters:
      - name: web_app_cluster
        connect_timeout: 0.25s
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: LEAST_REQUEST
        hosts: [{ socket_address: { address: web-app, port_value: 3000 }}]
      - name: proxy_app_cluster
        connect_timeout: 0.25s
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: RING_HASH
        hosts: [{ socket_address: { address: proxy-app, port_value: 3000 }}]