# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER openHAB

# Copy custom configuration file from the current directory
RUN rm /etc/nginx/conf.d/default.conf 
COPY ./nginx/nginx-ohc.conf /etc/nginx/conf.d/
COPY ./nginx/nginx-ohc-proxy.include /etc/nginx/
COPY ./nginx/nginx-ohc-redirects.include /etc/nginx/
COPY ./nginx/nginx-ohc-nameserver.template /etc/nginx/
COPY ./nginx/run.sh /
COPY ./openhab-cloud/public /var/www/html

CMD ["/run.sh"]